linkedin/dustjs

- Gruntfile.js
- lib/dust.js
> Add dust.version and bump it during grunt-bump

- lib/parser.js
- src/dust.pegjs
- test/jasmine-test/spec/coreTests.js
Squashed commits:
[c77dd80] added unit tests, revisions to negative number support
[1858cd9] Adding support for negative integers and floats in grammar
> Adding support for negative integers and floats in grammar

- test/test.html
#562  fix the test pages.
please ignore #564
> update test page (even though it's legacy)

- _includes/head.html
Preserve path, query string, and hash during forwarding.
> Forward linkedin.github.io/dustjs to dustjs.com

- _includes/head.html
What was the point of that last commit, anyway...
> Strip the /dustjs

- .gitignore
- README.md
- _config.yml
- _includes/footer.html
- scss/components/_footer.scss
- styles/main.css
because ribbons are cool. see https://github.com/blog/273-github-ribbons
> Add github ribbon

- scss/components/_content.scss
- scss/components/_nav.scss
- scss/main.scss
- scss/partials/_layout.scss
- styles/main.css
added margin to line numbers where code snippets are highlighted by coderay
fixed helper API page issue with nested <ul> tags (+1 squashed commit)
Squashed commits:
[c501954] Un-fixing nav on desktop
> Un-fixing nav on desktop 

- docs/dustc-api.md
- scss/components/_content.scss
> Update dustc documentation

- docs/template-api.md
> Add documentation on comments

- examples/basic-browser/README.md
- examples/streaming-hoffman/README.md
- examples/streaming-incremental/README.md
- examples/streaming-incremental/app.js
- examples/streaming-incremental/package.json
- examples/streaming-incremental/views/hello.dust
- examples/streaming-incremental/views/index.dust
- examples/streaming/app.js
> Clarify a few examples and add a new explicitly-incremental streaming example

- guides/context-helpers.md
- guides/contexts.md
- guides/dust-helpers.md
- guides/setup.md
> Update docs with some misc fixes

- .travis.yml
Ref http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
> Move to Travis CI Container builds

- _includes/nav.md
- docs/dustc-api.md
- guides/getting-started.md
- guides/rendering.md
- guides/setup.md
- scss/components/_content.scss
- styles/main.css
> Add "Compiling and Rendering" doc, and add docs for changes from #613

- lib/parser.js
- src/dust.pegjs
Pull out all the repetitive line/column adding into a function.
Normalize the style of function blocks.
> clean up PEG grammar a little bit

- bin/dustc
> dustc always creates templates with forward slashes

- .gitignore
- _config.yml
- _sass/components/_content.scss
- _sass/partials/_colors.scss
- _sass/partials/coderay.scss
- css/main.scss
- docs/api.md
- docs/helper-api.md
- docs/template-api.md
- guides/context-helpers.md
- guides/setup.md
> Configure CodeRay syntax highlighter

- docs/dustc-api.md
> Add note about dustc forward slash behavior

- examples/amd/README.md
- examples/amd/package.json
- examples/commonjs/package.json
Use an npm script instead of the repo's `dustc`
[ci skip]
> Update AMD example

- lib/parser.js
- src/dust.pegjs
> Grammar: s/char/character/ to avoid using a reserved name

- Gruntfile.js
- README.md
- package.json
- test/lib/jsreporter.js
> Add saucelabs integration

- .gitignore
- Gruntfile.js
- bower.json
- lib/dust.js
- test/templates/all.js
Adding `resume` maintains compatibility with old Node streams and Streams2 streams, as well as Highland.
Closes #663
> Be slightly pickier about what Dust thinks a Stream is.

- lib/dust.js
- test/helpers/template.helper.js
- test/templates/all.js
> Pass the current context to filters

- guides/getting-started.md
> Mention `$idx` and `$len` variables

- lib/dust.js
> provides stack trace at DEBUG log level

- .travis.yml
- lib/dust.js
> Fix stacktrace logging for IE8

- lib/dust.js
- test/core.spec.js
> When rendering with a Context object, use the templateName provided by the template

- package.json
Refer https://github.com/linkedin/dustjs/issues/807
> Dependency update: chokidar
