linkedin/dustjs

lib/dust.js, test/jasmine-test/spec/coreTests.js
This prevents a potential XSS attack.
Closes #449
=> Stringify things before calling escapeHtml on them in case their stringified representation contains HTML

lib/dust.js, test/jasmine-test/spec/coreTests.js
Since most templates write into html context or worse, a script tag, let's add a few extra characters to escape.
slight refactor to expose a `dust.escapeJSON` method
```
<script> var x = {foo|js}</script>
```
=> escape values when using json filter

lib/compiler.js, test/jasmine-test/spec/coreTests.js
Since the compiler was not interpreting template names when emitting
javascript code with those as literals, and instead merely concatenating
string delimiters onto the end, template names ending in a backslash
or containing a newline or double quotes would cause a parser failure
when loading the compiled template.
This additionally escapes the null character, as some browsers will omit
it during parsing, making the template name not make a round-trip from
what was specified to what is cached.
=> Escape template names

bin/dustc
This resolves #542 by replacing util.print/util.puts with console.log.
=> Replaced util.print/util.puts with console.log

lib/compiler.js, test/jasmine-test/spec/coreTests.js
=> Fix the output of format (whitespace-only) blocks inside inline partials

_includes/nav.md
Removing extra link to downloading and setup guide from the navigation.
=> Removed Download & Setup link from the guides list

lib/dust.js, test/jasmine-test/spec/coreTests.js
This function behaves similarly to dust.helpers.tap but is part of core and requires no passing of chunk and context parameters.
Closes #554
=> Add Context#resolve

lib/dust.js, test/jasmine-test/spec/coreTests.js, test/jasmine-test/spec/renderTestSpec.js
This is a starting point for discussion, probably not final.
I added the `clone` method because `Chunk#partial` can resolve partials asynchronously, so you run into closure issues if you don't clone the working context. But it's useful anyways.
Closes #558
=> Add `context.clone` and `context.pop`

.gitignore, bower.json, examples/amd/.bowerrc, examples/amd/README, examples/amd/bower.json, examples/amd/index.html, examples/amd/lib/main.js, examples/amd/views/hello.dust, examples/amd/views/version.dust, examples/basic-browser/.bowerrc, examples/basic-browser/README, examples/basic-browser/bower.json, examples/basic-browser/index.html, examples/basic-browser/lib/main.js, examples/basic-browser/views/hello.dust, examples/basic-browser/views/version.dust, examples/basic-node/README, examples/basic-node/app.js, examples/basic-node/package.json, examples/streaming-hoffman/README, examples/streaming-hoffman/app.js, examples/streaming-hoffman/package.json, examples/streaming-hoffman/views/dust-site.dust, examples/streaming-hoffman/views/hello.dust, examples/streaming/README, examples/streaming/app.js, examples/streaming/package.json, examples/streaming/views/dust-site.dust, examples/streaming/views/hello.dust
Simple browser
AMD in the browser
Super-simple Node
Streaming with Express
Streaming with Hoffman
Closes #575
=> Adding examples!

bin/dustc, package.json
Watches the existing files and reruns compilation if they change.
Closes #553
=> Add --watch support to dustc

lib/dust.js, test/core.js, test/jasmine-test/spec/coreTests.js, test/jasmine-test/spec/renderTestSpec.js
Dust handles thenables (promises) in context, either directly or as the return value of a context helper. Dust will reserve a chunk asynchronously for the eventual return value of the promise.
If the promise is invoked as a reference, the reference will become the eventual return value. If the promise is invoked as a section, the eventual return value will be pushed onto the stack.
This allows Dust to integrate with third-party modules that don't know what Dust is, while still allowing those modules to make use of Dust's asynchronous nature seamlessly.
Closes #568
=> Thenable support

Gruntfile.js, lib/dust.js, package.json, test/core.js, test/jasmine-test/spec/cli/lib/matchers.js, test/jasmine-test/spec/coreTests.js, test/jasmine-test/spec/renderTestSpec.js, test/server.js
Similar to linkedin/dustjs-helpers#119
Normalizes all log messages, removes some spew, fixes some logs that would never be logged, and removes the indexOf shim in favor of a map lookup.
Closes #485
=> Clean up / refactor logging

Gruntfile.js, lib/dust.js, package.json, test/core.js, test/jasmine-test/spec/cli/lib/matchers.js, test/jasmine-test/spec/coreTests.js, test/jasmine-test/spec/renderTestSpec.js, test/server.js
Depends on #579, don't pull until that one is.
Uses the same UMD pattern as parser and compiler now, instead of a slightly different one. `root` should only be used to refer to the browser window, not Node's `global`, so now we use `console` directly instead of `root.console`.
Fixed up tests to ensure that we call dust.log even though debugLevel is turned off to avoid spam, to make sure that we test the code path.
Fixes #500 by removing the IIFE in favor of `this`.
Fixes #524 by allowing DEBUG=dust to be set on the command line to turn on debugging.
=> Refactor main Dust module's global context

test/jasmine-test/spec/coreTests.js, test/rhino/rhinoTest.js
Right now even if Rhino fails, the build succeeds. Guess no one ever broke just Rhino before.
(However, Dust itself was never broken, just the unit tests.)
=> Allow Rhino test failures to break the build (and fix a test typo that broke Rhino)

bin/dustc, bower.json, index.js, lib/README.md, package.json, test/server.js
This is the most common Node convention. It also makes it very clear that the `server.js` file is for Node by moving it away from the `lib` directory.
=> Move lib/server to index

Gruntfile.js, package.json
Tested to confirm that the generated changelog is the same as before.
Closes #600
=> Add grunt-github-changes plugin to automatically update changelog before releases

lib/dust.js, test/jasmine-test/spec/coreTests.js
There's one edge case that `context.resolve()` didn't hit.
If you have a function in context (not a generated Dust body function) that returns a chunk, the chunk is not evaluated.
```
{#foo param="{func_returns_chunk} world"/} {! works because the whole string turns into a generated body function !}
{#foo param=func_that_returns_value /} {! works because the func doesn't return a Chunk !}
{#foo param=func_that_returns_chunk /} {! [object Object] !}
```
PR fixes this edge case.
=> Fix behavior of `Context#resolve` when resolving a context function that returns a Chunk

Gruntfile.js, bin/dustc, index.js, lib/compiler.js, lib/dust.js, test/core.js, test/jasmine-test/spec/cjsSpec.js, test/jasmine-test/spec/cli/cliSpec.js, test/jasmine-test/spec/cli/lib/matchers.js, test/jasmine-test/spec/coreTests.js, test/jasmine-test/spec/renderTestSpec.js
OK, there are quite a few changes in here.
This is the first step towards treating compiled templates as first-class citizens in Dust. We want to be able to pass around compiled templates and render them without having to worry about registering them under a specific name.
* `dust.render` and `dust.stream` now accept a compiled template function in addition to a template name.
* `dust.compile` no longer requires a template name, and will compile an anonymous template without one (so `--name` is no longer required for dustc either)
* `dust.load` is removed from the public API
* ~~`dust.compileFn` is removed completely~~
* `dust.renderSource` is moved to the compiler, so it's only included in dust-full now (Fixes #412)
* add `dust.isTemplateFn`
* add `dust.config.cache = true`, set to …
=> Refactor template compilation

lib/dust.js, test/core.js, test/jasmine-test/spec/coreTests.js
https://github.com/linkedin/dustjs-helpers/pull/128 showed that it's possible to get nasty Stacks that only contain `undefined` when you use `dust.makeBase`. As much as possible this behavior should be avoided.
Now the only way you can get one is if you explicitly push `undefined` onto a context stack... but then it's your own fault.
Context pop and clone exercise a lot of context creation behavior, and we didn't have tests for them yet anyways, so killing all the birds with one PR.
=> Try to avoid creating Stacks with no content when possible

lib/compiler.js, lib/dust.js, test/jasmine-test/spec/coreTests.js
When scoping a partial with a dynamic name to a context like this:
{>"{partial}":context /}
The evaluation of the partial name was done in `context` instead of the current scope.
Fixes #262
Closes #261
=> Resolve dynamic partial names via original context

.travis.yml, package.json
=> Drop Node 0.8

lib/dust.js, test/jasmine-test/spec/coreTests.js
This allows templates compiled with an older version of the compiler to continue working, even if using the 2.7 renderer.
Only templates with partials are affected.
=> Preserve compiler backwards compatibility with pre-2.7 versions

.travis.yml, Gruntfile.js, package.json, test/jasmine-test/spec/cli/cliSpec.js
Temporary fix for #649 while we wait for an upstream fix.
=> Pin jasmine@2.2.x for grunt-jasmine-nodejs

lib/dust.js, test/core.js, test/jasmine-test/spec/cjsSpec.js
Currently you can either call `cb()`, in which case Dust will try to load the original name from cache,
or `cb(null, src)`, and Dust will try to compile `src` and register it under the original name.
Sometimes, you might want to dynamically load one of several templates based on the original name.
This change adds `cb(null, compiledTemplate)` so you can load any template from cache or the filesystem,
register it manually (or not at all), and render it.
The returned template will NOT be registered under the original name.
=> Add a `cb(null, compiledTemplate)` signature to `dust.onLoad`

lib/dust.js, test/core.js
Because we're manually manipulating the stack to add $idx and $len, we have to check here too and not just in Context#get
Closes #652
=> Fix array iteration when context is undefined

lib/compiler.js, lib/dust.js, lib/parser.js, src/dust.pegjs, test/helpers/template.helper.js, test/templates/all.js
Previously returning a primitive would crash rendering with no way to recover.
Primitives are always HTML-escaped ~~with no way to turn that off~~ unless you override with a `filters` param. If you need to adjust the escaping, you need to return a Chunk and do the work yourself.
Closes #645
=> Allow helpers to return primitives

lib/dust.js, test/templates/all.js
This was a missed case where section should have been used instead of render.
Closes #674
=> If a Promise is resolved with an array, iterate over it instead of rendering the whole array at once.

lib/dust.js, test/templates/all.js
=> Prioritize resolution of .then 

lib/dust.js, test/core.spec.js
=> Don't use instanceof to determine if a Context is a Context

lib/compiler.js, lib/parser.js, src/dust.pegjs
Since we are now using peg 0.9, it'll be useful to have the end line, end column and offset. Offset is useful for parser authors who want to splice on the file buffer (get the template text for a helper for instance).
Up for discussion:
* I'm dumping all of location into the location property of the peg node for max back compat. It's meta data so it seems cleaner.
* I'm removing the extra line/column from the ast so it's a breaking change
=> place location provided by peg 0.9 onto the AST

lib/dust.js, test/templates.spec.js, test/templates/all.js
I logged this as bug #752 - {?exists/} behavior different when using promises.
=> {?exists} and {^exists} now supports values from a promise

package.json
Looks like the `cli` project didn't change their interface so no changes are needed with *dustjs*. This should resolve the `nsp` security alert and make *dustjs* secure.
Please merge and publish to npm, thanks
-=Dan=-
=> Decrease security vulnerabilities by upgrading cli dependency (#754 #748)
